#!/usr/bin/env node
// Bulk-import a directory of full-resolution photographer JPEGs into R2 + D1
// as if the photographer had uploaded them through /p/<token>/<eventId>.
// Resizes via sharp into a thumb (400px) + display (1600px) WebP, uploads
// both to local R2, then writes INSERT statements to local D1 via wrangler.
//
// Usage:
//   node scripts/import-photos.mjs \
//     --src "/path/to/photos" \
//     --event evt_cup2 \
//     --photographer photog_peter \
//     [--photographer-name "Peter Zuidmeer"]
//
// The --src/--event/--photographer flags are required. If the photographer
// id doesn't exist, the script inserts a stub row you can edit later in
// /admin/photographers.

import { spawn } from "node:child_process";
import { readdir, mkdir, writeFile, stat, rm } from "node:fs/promises";
import { join, basename, extname, dirname } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const PROJECT_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

const args = parseArgs(process.argv.slice(2));
const { src, event: eventId, photographer: photogId } = args;
const photogName = args["photographer-name"] ?? null;
if (!src || !eventId || !photogId) {
  console.error("Usage: import-photos.mjs --src DIR --event ID --photographer ID [--photographer-name NAME]");
  process.exit(1);
}

const BUCKET = "cscc-media";
const DB_NAME = "cscc";
const RESIZE_CONCURRENCY = 6;
const UPLOAD_CONCURRENCY = 1;  // Multiple wrangler procs contend on Miniflare state.
const THUMB_WIDTH = 400;
const DISPLAY_WIDTH = 1600;

const tmpDir = await mkdir(join(tmpdir(), `cscc-import-${process.pid}`), { recursive: true });
const tmp = tmpDir ?? join(tmpdir(), `cscc-import-${process.pid}`);

const entries = (await readdir(src))
  .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
  .sort();
console.log(`Found ${entries.length} source file(s) in ${src}`);

if (entries.length === 0) process.exit(0);

// ---------- Phase 1: resize + write WebP to /tmp ----------
console.log("Resizing…");
const records = [];
let resized = 0;
await runConcurrent(entries, RESIZE_CONCURRENCY, async (filename) => {
  const sourcePath = join(src, filename);
  const stem = basename(filename, extname(filename));
  const stat1 = await stat(sourcePath);
  const photoId = `p_${eventId}_${stem}`.replace(/[^A-Za-z0-9_]/g, "_").slice(0, 32);

  const thumbPath = join(tmp, `${photoId}_thumb.webp`);
  const displayPath = join(tmp, `${photoId}_display.webp`);

  // Skip re-resize if both outputs already exist (resume support).
  let meta;
  try {
    await Promise.all([stat(thumbPath), stat(displayPath)]);
    meta = await sharp(sourcePath, { failOn: "none" }).metadata();
  } catch {
    // `.rotate()` (no args) bakes EXIF Orientation into the pixels so the
    // emitted WebP renders upright — browsers don't honor EXIF on WebP, so
    // portrait phone shots would otherwise display sideways.
    const img = sharp(sourcePath, { failOn: "none" }).rotate();
    meta = await img.metadata();
    await img.clone().resize({ width: THUMB_WIDTH }).webp({ quality: 78 }).toFile(thumbPath);
    await img.clone().resize({ width: DISPLAY_WIDTH }).webp({ quality: 82 }).toFile(displayPath);
  }

  const thumbKey = `events/${eventId}/${photoId}/thumb.webp`;
  const displayKey = `events/${eventId}/${photoId}/display.webp`;

  records.push({
    photoId,
    filename,
    thumbPath, displayPath,
    thumbKey, displayKey,
    width: meta.width ?? null,
    height: meta.height ?? null,
    takenAt: stat1.mtimeMs,
  });

  resized++;
  if (resized % 20 === 0 || resized === entries.length) {
    process.stdout.write(`  resized ${resized}/${entries.length}\r`);
  }
});
process.stdout.write("\n");

// ---------- Phase 2: upload to R2 via wrangler ----------
console.log("Uploading to R2…");
let uploaded = 0;
await runConcurrent(records, UPLOAD_CONCURRENCY, async (r) => {
  await wranglerWithRetry(["r2", "object", "put", `${BUCKET}/${r.thumbKey}`,
    "--file", r.thumbPath, "--content-type=image/webp", "--local"]);
  await wranglerWithRetry(["r2", "object", "put", `${BUCKET}/${r.displayKey}`,
    "--file", r.displayPath, "--content-type=image/webp", "--local"]);
  uploaded++;
  if (uploaded % 10 === 0 || uploaded === records.length) {
    process.stdout.write(`  uploaded ${uploaded}/${records.length}\r`);
  }
});
process.stdout.write("\n");

// ---------- Phase 3: write SQL and apply ----------
console.log("Writing D1 rows…");
const escape = (v) => v === null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const nowSec = Math.floor(Date.now() / 1000);

// upload_token uses hex(randomblob(16)) so reseeding produces a fresh token
// for new photographers — existing rows are left untouched by INSERT OR IGNORE.
const upserts = [];
upserts.push(`-- Auto-generated by import-photos.mjs at ${new Date().toISOString()}`);
upserts.push(`INSERT OR IGNORE INTO photographers (id, slug, name, active, upload_token, created_at, updated_at)`);
upserts.push(`VALUES (${escape(photogId)}, ${escape(photogId.replace(/^photog_/, ""))},`);
upserts.push(`        ${escape(photogName ?? photogId.replace(/^photog_/, "").replace(/_/g, " "))}, 1,`);
upserts.push(`        lower(hex(randomblob(16))), ${nowSec}, ${nowSec});`);

upserts.push(`INSERT OR IGNORE INTO event_photographers (id, event_id, photographer_id, created_at)`);
upserts.push(`VALUES (${escape(`ep_${eventId}_${photogId}`)}, ${escape(eventId)}, ${escape(photogId)}, ${nowSec});`);

for (const r of records) {
  const takenAtSec = Math.floor(r.takenAt / 1000);
  upserts.push(
    `INSERT OR REPLACE INTO photos
       (id, event_id, photographer_id, filename,
        exif_taken_at, uploaded_at, width, height,
        r2_key_thumb, r2_key_display, r2_key_full, sort_order, status)
     VALUES (${escape(r.photoId)}, ${escape(eventId)}, ${escape(photogId)},
       ${escape(r.filename)},
       ${takenAtSec}, ${nowSec}, ${r.width ?? "NULL"}, ${r.height ?? "NULL"},
       ${escape(r.thumbKey)}, ${escape(r.displayKey)}, ${escape(r.displayKey)},
       NULL, 'live');`,
  );
}

// Persist the SQL to seeds/imports/ so `db:seed:local` can re-apply it
// after a D1 wipe (the R2 objects survive a D1 reset).
const importsDir = join(PROJECT_ROOT, "seeds", "imports");
await mkdir(importsDir, { recursive: true });
const sqlPath = join(importsDir, `${eventId}_${photogId}.sql`);
await writeFile(sqlPath, upserts.join("\n") + "\n");
console.log(`Wrote ${sqlPath}`);

console.log("Applying SQL to local D1…");
await wrangler(["d1", "execute", DB_NAME, "--local", `--file=${sqlPath}`]);

// Clean up resized WebP scratch dir (we keep the SQL file).
await rm(tmp, { recursive: true, force: true });

console.log(`Done. Imported ${records.length} photo(s) into event ${eventId}.`);

// ---------- helpers ----------
function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith("--")) { out[key] = next; i++; }
      else { out[key] = true; }
    }
  }
  return out;
}

async function runConcurrent(items, n, fn) {
  let i = 0;
  const workers = Array.from({ length: Math.min(n, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      await fn(items[idx]);
    }
  });
  await Promise.all(workers);
}

function wrangler(args) {
  return new Promise((resolve, reject) => {
    const child = spawn("pnpm", ["wrangler", ...args], {
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stderr = "";
    child.stderr.on("data", (d) => stderr += d.toString());
    child.on("exit", (code) => {
      if (code !== 0) reject(new Error(`wrangler ${args.join(" ")} failed (${code}): ${stderr}`));
      else resolve();
    });
  });
}

async function wranglerWithRetry(args, attempts = 3) {
  for (let i = 0; i < attempts; i++) {
    try {
      await wrangler(args);
      return;
    } catch (err) {
      if (i === attempts - 1) throw err;
      await new Promise((r) => setTimeout(r, 250 * (i + 1)));
    }
  }
}
