#!/usr/bin/env node
// Applies the main demo seed plus any per-import SQL files in seeds/imports/.
// Used by `pnpm db:seed:local`. The imports/ files are generated by
// scripts/import-photos.mjs and persist photo INSERTs across D1 resets
// (since R2 objects survive a D1 wipe).

import { spawn } from "node:child_process";
import { readdir, stat } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const DB = "cscc";

async function applyFile(file) {
  process.stdout.write(`→ ${file}\n`);
  await new Promise((resolve, reject) => {
    const proc = spawn("pnpm", ["wrangler", "d1", "execute", DB, "--local", `--file=${file}`], {
      cwd: ROOT,
      stdio: ["ignore", "ignore", "inherit"],
    });
    proc.on("exit", (code) => code === 0 ? resolve() : reject(new Error(`failed (${code})`)));
  });
}

await applyFile(join(ROOT, "seeds", "demo.sql"));

const importsDir = join(ROOT, "seeds", "imports");
try {
  await stat(importsDir);
  const files = (await readdir(importsDir)).filter((f) => f.endsWith(".sql")).sort();
  for (const f of files) {
    await applyFile(join(importsDir, f));
  }
  if (files.length > 0) console.log(`Applied ${files.length} import file(s).`);
} catch {
  // No imports/ dir yet — that's fine.
}
